// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessingService.DAL;

#nullable disable

namespace ProcessingService.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20260917062821_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProcessingService.Models.DTOs.StationInformationDTO", b =>
                {
                    b.Property<string>("StationId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<double>("Lat")
                        .HasColumnType("double");

                    b.Property<double>("Lon")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StationId");

                    b.ToTable("StationsInformation");
                });

            modelBuilder.Entity("ProcessingService.Models.DTOs.VehicleTypesDTO", b =>
                {
                    b.Property<string>("VehicleTypeId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PropulsionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("VehicleTypeId");

                    b.ToTable("VehicleTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
