// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessingService.DAL;

#nullable disable

namespace ProcessingService.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    partial class MySqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProcessingService.Models.DTOs.StationInformationDTO", b =>
                {
                    b.Property<string>("StationId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<double>("Lat")
                        .HasColumnType("double");

                    b.Property<double>("Lon")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StationId");

                    b.ToTable("StationsInformation");
                });

            modelBuilder.Entity("ProcessingService.Models.DTOs.StationStatusDTO", b =>
                {
                    b.Property<string>("StationId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsRenting")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsReturning")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("LastReported")
                        .HasColumnType("bigint");

                    b.Property<int>("NumBikesAvailable")
                        .HasColumnType("int");

                    b.Property<int>("NumDocksAvailable")
                        .HasColumnType("int");

                    b.HasKey("StationId");

                    b.ToTable("StationStatuses");
                });

            modelBuilder.Entity("ProcessingService.Models.DTOs.VehicleTypesDTO", b =>
                {
                    b.Property<string>("VehicleTypeId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PropulsionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("VehicleTypeId");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("ProcessingService.Models.DTOs.StationInformationDTO", b =>
                {
                    b.HasOne("ProcessingService.Models.DTOs.StationStatusDTO", "StationStatus")
                        .WithOne("StationInformation")
                        .HasForeignKey("ProcessingService.Models.DTOs.StationInformationDTO", "StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StationStatus");
                });

            modelBuilder.Entity("ProcessingService.Models.DTOs.StationStatusDTO", b =>
                {
                    b.Navigation("StationInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
